import { StyleSheet } from 'react-native';

export const ui = {
  bg: '#f8fafc',
  soft: '#f1f5f9',
  card: 'rgba(255,255,255,0.96)',
  text: '#0f172a',
  muted: '#64748b',
  line: 'rgba(148, 163, 184, 0.24)',
  primary: '#2563eb',
  primarySoft: 'rgba(37, 99, 235, 0.12)',
  danger: '#dc2626',
  dangerSoft: 'rgba(220, 38, 38, 0.08)',
  success: '#16a34a',
  successSoft: 'rgba(22, 163, 74, 0.12)',
  warning: '#d97706',
  warningSoft: 'rgba(217, 119, 6, 0.12)',
  dark: '#1e293b',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: ui.bg },
  scroll: { flexGrow: 1, padding: 16, gap: 16 },
  card: { backgroundColor: ui.card, borderWidth: 1, borderColor: ui.line, borderRadius: 24, padding: 24, gap: 16 },
  hero: { gap: 18 },
  loginShowcase: { backgroundColor: ui.primary, borderColor: 'rgba(255,255,255,0.12)' },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  brandMark: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: ui.primary },
  brandMarkText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  brandTitle: { color: ui.text, fontSize: 18, fontWeight: '800' },
  brandTitleOnDark: { color: '#fff', fontSize: 18, fontWeight: '800' },
  eyebrow: { color: ui.primary, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.2 },
  eyebrowDark: { color: '#fff', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.2 },
  pageTitle: { color: ui.text, fontSize: 30, lineHeight: 34, fontWeight: '800' },
  pageSubtitle: { color: ui.muted, fontSize: 15, lineHeight: 22 },
  heroTitle: { color: '#fff', fontSize: 34, lineHeight: 38, fontWeight: '800' },
  heroCopy: { color: 'rgba(255,255,255,0.8)', fontSize: 15, lineHeight: 24 },
  stack: { gap: 14 },
  field: { gap: 10 },
  label: { color: ui.text, fontSize: 14, fontWeight: '700' },
  input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 14, paddingHorizontal: 15, paddingVertical: 13, backgroundColor: '#fff', color: ui.text, fontSize: 16 },
  textarea: { minHeight: 130 },
  inputCompact: { paddingVertical: 10 },
  buttonRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  primaryButton: { alignItems: 'center', justifyContent: 'center', backgroundColor: ui.primary, borderRadius: 14, paddingHorizontal: 18, paddingVertical: 12 },
  primaryButtonText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  ghostButton: { alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: ui.line, borderRadius: 14, paddingHorizontal: 18, paddingVertical: 12 },
  ghostButtonText: { color: ui.text, fontSize: 14, fontWeight: '700' },
  secondaryButton: { alignItems: 'center', justifyContent: 'center', backgroundColor: ui.dark, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 11 },
  secondaryButtonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  dangerButton: { alignItems: 'center', justifyContent: 'center', backgroundColor: ui.dangerSoft, borderWidth: 1, borderColor: 'rgba(220, 38, 38, 0.12)', borderRadius: 14, paddingHorizontal: 16, paddingVertical: 11 },
  dangerButtonText: { color: ui.danger, fontSize: 14, fontWeight: '700' },
  errorBox: { backgroundColor: ui.dangerSoft, borderWidth: 1, borderColor: 'rgba(220, 38, 38, 0.12)', borderRadius: 16, padding: 14 },
  errorText: { color: ui.danger, fontSize: 14, lineHeight: 20 },
  sidebar: { gap: 18 },
  navStack: { gap: 8 },
  navLink: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 16 },
  navLinkActive: { backgroundColor: ui.primarySoft },
  navIcon: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: ui.soft },
  navIconText: { color: ui.primary, fontSize: 11, fontWeight: '800' },
  navLabel: { color: ui.muted, fontSize: 15, fontWeight: '600' },
  navLabelActive: { color: ui.primary },
  profileChip: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 18, backgroundColor: ui.soft },
  profileAvatar: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: ui.primary },
  profileAvatarText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  profileName: { color: ui.text, fontSize: 14, fontWeight: '700' },
  profileRole: { color: ui.muted, fontSize: 12, marginTop: 2 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  statCard: { minWidth: '47%', flexGrow: 1, backgroundColor: ui.card, borderWidth: 1, borderColor: ui.line, borderRadius: 20, padding: 22 },
  statTone: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  statToneText: { color: ui.text, fontSize: 11, fontWeight: '800' },
  tonePrimary: { backgroundColor: ui.primarySoft },
  toneWarning: { backgroundColor: ui.warningSoft },
  toneSuccess: { backgroundColor: ui.successSoft },
  toneDark: { backgroundColor: 'rgba(15, 23, 42, 0.08)' },
  panelTitle: { color: ui.text, fontSize: 24, fontWeight: '800' },
  statValue: { marginTop: 16, color: ui.text, fontSize: 30, fontWeight: '800' },
  statLabel: { marginTop: 6, color: ui.muted, fontSize: 14 },
  metricRing: { width: 220, height: 220, alignSelf: 'center', borderRadius: 999, backgroundColor: ui.primarySoft, alignItems: 'center', justifyContent: 'center' },
  metricRingInner: { width: 128, height: 128, borderRadius: 999, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  metricValue: { color: ui.text, fontSize: 34, fontWeight: '800' },
  listRow: { padding: 18, borderRadius: 18, backgroundColor: '#f8fbff', borderWidth: 1, borderColor: 'rgba(148, 163, 184, 0.18)', gap: 12 },
  summaryRow: { padding: 18, borderRadius: 18, backgroundColor: '#f8fbff', borderWidth: 1, borderColor: 'rgba(148, 163, 184, 0.18)', gap: 8 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  flexOne: { flex: 1 },
  itemTitle: { color: ui.text, fontSize: 16, fontWeight: '700' },
  muted: { color: ui.muted, fontSize: 14, lineHeight: 21 },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 6 },
  metaText: { color: ui.muted, fontSize: 13 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { borderRadius: 999, borderWidth: 1, borderColor: ui.line, backgroundColor: '#fff', paddingHorizontal: 12, paddingVertical: 8 },
  chipActive: { backgroundColor: ui.primarySoft, borderColor: 'rgba(37, 99, 235, 0.25)' },
  chipText: { color: ui.text, fontSize: 13, fontWeight: '600' },
  chipTextActive: { color: ui.primary },
  badge: { borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6 },
  badgeText: { fontSize: 12, fontWeight: '700', textTransform: 'capitalize' },
  emptyState: { padding: 30, borderRadius: 20, backgroundColor: ui.soft, alignItems: 'center' },
  emptyTitle: { color: ui.text, fontSize: 18, fontWeight: '700', textAlign: 'center' },
  emptyCopy: { color: ui.muted, fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 6 },
  divider: { height: 1, backgroundColor: ui.line, marginVertical: 4 },
});
